project:
  type: book
  output-dir: docs

book:
  title: "Exploring Julia"
  subtitle: "A problem-solving approach"
  author: "G. Vituri"
  date: "2023-06-27"
  chapters:
    - index.qmd
    - intro.qmd
    - vectors.qmd
    - functions.qmd
    - performance.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

