project:
  type: book
  output-dir: docs

book:
  title: "Exploring Julia"
  subtitle: "A problem-solving approach"
  author: "G. Vituri"
  date: "2023-06-27"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Basics"
    - vectors.qmd
    - functions.qmd
    - dataframes.qmd
    - performance.qmd

    - part: "Graphs"
    - part: "Machine learning"
    - part: "Neural networks"

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

